### ISSUE TITLE
Create a RAID 0 on instances with multiple ephemeral SSD volumes

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgcloud-core#14]

**Comment by jvivian** [comment]
You probably don't need a reminder but just in case it saves you having to look it up:

**Requirements:**  apt-get install mdadm

Unmount single SSD
1. sudo umount /dev/xvdb

Create RAID 
    2. sudo mdadm --create --verbose /dev/md0 --level=0 --raid-devices=2 /dev/xvdb /dev/xvdc

Format with EXT4 File System
    3. sudo mkfs.ext4 /dev/md0

Mount 
    4. sudo mount /dev/md0 /mnt

**Comment by diekhans** [comment]
my usual why curiosity questions:  why RAID to begin with.  Is it possible to ensure that the ephemeral SSD volumes are on separate devices?  If so, this might be a nice performance benefit

ZFS might be another option over ext4

**Comment by hannes-ucsc** [comment]
Thank you, John.

Mark, I'm doing this only for convenience, performance or redundancy. Some instance type have multiple SSDs but most images only mount one. Some images mount both, but on separate mount points. Since the volumes tend to be small, one always ends up full with space left on the other. For example, the spark-ec2 scripts assign one volume to HDFS and the other to Spark shuffle but it is not clear in advance how much space will be needed on each of them. So it's more practical to merge them without having to allocate a fixed amount to either.

Re FS: I'd appreciate any advice on choosing one. For ephemeral volumes I don't care about durability. I just want raw performance and don't want the FS to do anything that's bad for the SSD, like hot spots. On the other hand, I don't even know if I need to worry about that since the device is virtual and the hypervisor may already safeguard against it.

**Comment by diekhans** [comment]
I did a quick scan of FS benchmarks and with ZFS is faster in
some cases, ext4 looks like it wins in more.  I would give this
as a data point that it's not worth switch without more data.

My guess is that a file system where you can turn off all
consistency mechanisms would be a win for ephemeral volumes.

My suggestion is to do what is easiest and then see were we are
at with real workloads.  We might be able to get help from the
Storage System people at UCSC.  Could be a good student project
to benchmark.
